PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX tr: <http://example.org/trace#>
PREFIX : <http://example.org#>

SELECT ?match_num ?total_num ?perc
WHERE { 
    {
        SELECT (COUNT(?t0) as ?match_num)
        WHERE {
            << :a1 tr:next :a2 >> tr:in ?t0 .
            << :a2 tr:next :a3 >> tr:in ?t0 .
        }
    }
    {
        SELECT (COUNT(DISTINCT ?t) as ?total_num)
        WHERE {
            << ?x ?y ?z >> tr:in ?t
        }
    }
    BIND ( ( ?match_num / ?total_num ) AS ?perc )
}